/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#0C1282",
        "on-primary": "#ffffff",
        "primary-container": "#e0e1ff",
        "on-primary-container": "#00006e",
        "primary-fixed": "#e0e0ff",
        "on-primary-fixed": "#00003b",
        "secondary": "#5a5d72",
        "on-secondary": "#ffffff",
        "secondary-container": "#dfe1f9",
        "on-secondary-container": "#171a2c",
        "tertiary": "#76546e",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffd7f3",
        "on-tertiary-container": "#2d1229",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#410002",
        "outline": "#767680",
        "outline-variant": "#c5c6d0",
        "background": "#fbf8ff",
        "on-background": "#1b1b21",
        "surface": "#fbf8ff",
        "on-surface": "#1b1b21",
        "surface-dim": "#ded9e0",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f7fb",
        "surface-container": "#eeedf4",
        "surface-container-high": "#e8e8ec",
        "surface-container-highest": "#e2e2e6",
        "surface-variant": "#e2e2e6",
        "on-surface-variant": "#45474a",
        "inverse-surface": "#2f3033",
        "inverse-on-surface": "#f1f0f4",
        "inverse-primary": "#bfc2ff",
        "surface-tint": "#0c1282",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
    },
  },
  plugins: [],
};
